#!/bin/sh
HOST=$(hostname)
DIRS="/home/aparicio"
[[ $USER == root ]] && DIRS="$DIRS /etc /var"

BACKUP_DIR="/mnt/externo1/backups"
NEW="$HOST.$(date +%Y.%m.%d.%H.%M.%S)"

echo "Backup $DIRS to $BACKUP_DIR/$NEW"
rsync --archive --one-file-system --hard-links --human-readable  \
	--numeric-ids --delete --delete-excluded --progress --compress \
	--exclude-from=/home/aparicio/.rsync_exclude.txt \
	--include-from=/home/aparicio/.rsync_include.txt \
	--link-dest=../$HOST.last \
	$DIRS $BACKUP_DIR/$NEW

ln -sfn $BACKUP_DIR/$NEW $BACKUP_DIR/$HOST.last
