#!/bin/sh
# Helps "transfering" a file between shells by X selection

COLOR1="\033[1;31m" # RED
COLOR2="\033[1;32m" # GREEN
RESET="\033[0m"

echo -e " > ${COLOR1}Command${RESET} copied to clipboard." \
        "Middle-click on the destination and press ${COLOR1}Enter${RESET}."

# This blocks until the selection is pasted anywhere
echo -n "cat | base64 -d | bunzip2 > $1" | xclip -i -loops 1 -verbose 2>/dev/null


echo -e " > ${COLOR2}Content${RESET} copied to clipboard." \
        "Middle-click on the destination and press ${COLOR2}Ctrl+D${RESET}."

cat $1 | bzip2 | base64 | xclip -i
