#!/bin/sh

if [ $# == 0 ]; then echo "\
Copy:	clip <src> <dest1> <dest2> ...
Print:	clip <src>
Write:	... | clip - <dest>
Names:	sel, cli, sec, buf, clear, -"
fi

declare -A a
a[sel]="xclip -selection primary -o -i"
a[cli]="xclip -selection clipboard -o -i"
a[sec]="xclip -selection secondary -o -i"
a[buf]="xclip -selection buffer-cut -o -i"
a[clear]="echo -n"
a[-]="cat"

ARGS=($@)
if [[ ${@:$#} == all ]]; then
	ARGS=(${@:1:$#-1} sel cli sec buf)
fi

if [ $# == 1 ]; then
	ARGS=($ARGS -)
fi

for i in ${ARGS[*]:1}; do
	${a[${ARGS[0]}]/-i/} | ${a[$i]/-o/}
done
