#!/bin/sh

if [ $# == 0 ]; then echo "\
Copy:	clip <from> <to>
Print:	clip <name>
Write:	... | clip <name>
Names:	sel, cli, sec, buf, clear, print"
fi

declare -A a
a[sel]="xclip -selection primary -o -i"
a[cli]="xclip -selection clipboard -o -i"
a[sec]="xclip -selection secondary -o -i"
a[buf]="xclip -selection buffer-cut -o -i"
a[clear]="echo"
a[print]="cat"

ARGS=($@)
if [[ ${@:$#}  == all ]]; then
	ARGS=(${@:1:$#-1} sel cli sec buf)
fi

if [ ! -t 0 ]; then
	cat | ${a[${ARGS[0]}]/-o/}
elif [ $# == 1 ]; then
	ARGS=($ARGS print)
fi

for i in ${ARGS[*]:1}; do
	${a[${ARGS[0]}]/-i/} | ${a[$i]/-o/}
done
