#!/bin/bash
# Runs a command when a file or files in directory are modified

path="$1"
shift
prog="$@"

if [ -d "$path" ]; then
	IS_DIR=1
else
	IS_DIR=0
fi

# If the command is not specified, try to guess it
if [ -z "$prog" ]; then

	if [ "$IS_DIR" = 1 ]; then

		if [ -f Makefile ]; then
			prog="make"
		fi

	else

		case $path in
			*.tex)
				prog="pdflatex -halt-on-error" ;;
		esac

	fi
fi

if [ -z "$prog" ]; then
	echo "Don't know what command to run"
	exit
fi

while :; do

	read directory operation file < <(inotifywait --quiet --recursive -e create -e modify $path)

	if [ "$IS_DIR" = 1 ]; then

		if [[ "$file" =~ ^[0-9]{4}$ ]]; then
			echo "Skipping '$file' (vim temp)"

		else
			echo "Waiting for '$file' to be available"
			while [ ! -f $directory/$file ]; do
				:
			done

			echo "Running '$prog'" >&2
			# Eval is neeed to process shell file redirections
			eval $prog
		fi

	else
		# Wait for the file to be available
		while [ ! -f $path ]; do
			:
		done

		echo "Running $prog $path" >&2
		eval $prog $path
	fi
done
