#!/usr/bin/awk -f
BEGIN {
	FS="="
	cmd = "mplayer -vo null -ao null -frames 0 -identify '" ARGV[1] "' 2>/dev/null"
	while (cmd | getline)
		if ($1 == "ID_LENGTH") {
			H = int($2 / 3600);
			M = int(($2 - H * 3600) / 60);
			S = int($2 % 60);
			printf "%d:%02d:%02d\n", H, M, S
		}
}
