#!/bin/sh
[[ -z $1 ]] && echo "Usage: mkscript <file> <language>" && exit
[[ -e $1 ]] && echo "File $1 already exists!" && exit

PROG=sh
[[ ! -z $2 ]] && PROG=$2

echo "#!$(which $PROG)" > $1
chmod +x $1
