#!/bin/bash

function mouse_usb_port() {
	for port in /sys/bus/usb/devices/?-?.?; do
		for device in ${port}/?-?.?:?.?; do
			read class < ${device}/bInterfaceClass
			read subclass < ${device}/bInterfaceSubClass
			read protocol < ${device}/bInterfaceProtocol
			if [[ $class == 03 && $subclass == 01 && $protocol == 02 ]]; then
				echo $port
				return
			fi
		done
	done
}

dir="$(mouse_usb_port)/power"
control="${dir}/control"
auto="${dir}/autosuspend"

case "$1" in

	"auto")
		echo on > $control
		echo 300 > $auto
		echo "auto" > $control
		;;

	"on")
		echo "on" > $control
		;;

	 "off")
		echo 0 > $auto
		echo auto > $control
		sleep 0.01
		echo 300 > $auto
		;;
	*)
		echo "Usage: mouse [auto|on|off]"
esac
