#!/usr/bin/awk -f
BEGIN {
	dir = "/sys/bus/usb/devices/2-1.1/power/"
	control = dir "control"
	auto = dir "autosuspend"

	switch (ARGV[1]) {
		case "auto":
			print "on" > control
			print 300 > auto
			print "auto" > control
			break
		case "on":
			print "on" > control
			break
		case "off":
			print 0 > auto
			print "auto" > control
			system("sleep 0.01")
			print 300 > auto
			break
		default:
			print "Usage: mouse [auto|on|off]"
	}
}
