#!/usr/bin/gawk -f

# Shows the number of movies seen for each year of release
# Accepts a file with one movie per line with the following format:
# title (year)

$1 && $1 != "//" {
	match($NF, "\\(([0-9]+)\\)", a)
	year = a[1]
	if (year)
		y[year]++;
	else
		print "##### Year missing ##### " $0
}

END {
	PROCINFO["sorted_in"] = "@ind_num_asc"
	for (year in y)
		print year, y[year]
}
