#!/bin/bash
user=aparicio
ARGS=${@:1:${#@}-2}
TITLE=${@:${#@}-1:1}
MSG=${@:${#@}}

export XAUTHORITY=/home/$user/.Xauthority

if [ $EUID == 0 ]; then
	su $user -c "notify-send $ARGS '$MSG'"
else
	notify-send $ARGS "$TITLE" "$MSG"
fi
