#!/bin/sh

if [ ! $1 ]; then
	echo "Usage: scanner <filename>"
	exit
fi

DEFAULT=200

echo "Resolution: 100|150|200|300|400|600|1200|2400|4800|9600dpi"
echo -n "(Enter for $DEFAULT) ? "
read RES

if [ -e $RES ]; then
	RES=$DEFAULT
fi

if [ ${1#*.} = "png" ]; then
	scanimage --resolution $RES -p | pnmtopng > $1
	chown aparicio $1
elif [ ${1#*.} = "pdf" ]; then
	scanimage --resolution $RES -p | pnmtops > $1
	cd $(dirname $1)
	ps2pdf $1
fi
