#!/bin/sh

if [ ! $1 ]; then
	echo "Usage: scanner <filename>"
	exit
fi

DEFAULT=150

echo "Resolution: 75|100|150|300|600|1200dpi"
echo -n "(Enter for $DEFAULT) ? "
read RES

if [ -e $RES ]; then
	RES=$DEFAULT
fi

CMD="scanimage --mode Color --resolution $RES -p"

if [ ${1#*.} = "png" ]; then
	$CMD | pnmtopng > $1

elif [ ${1#*.} = "pdf" ]; then
	$CMD | pnmtops | ps2pdf - $1
fi
