#!/bin/sh
DIR="${HOME}/imagens/screenshots"
NAME="$DIR/$(date +%Y-%m-%d-%H-%M-%S).png"

if [ ! -d "${DIR}" ]; then
	mkdir -p "${DIR}"
fi

case $1 in
	scr*)  scrot    "${NAME}" ;;
	area) scrot -s "${NAME}" ;;
	win*)  scrot -u "${NAME}" ;;
	*)
		echo "Usage: screenshot [scr|area|win]"
		exit
		;;
esac

notify-send "Screenshot taken!" $NAME
ln -sf "${NAME}" "${DIR}/last.png"
