#!/bin/sh
DIR="${HOME}/imagens/screenshots"
NAME="$DIR/$(date +%Y-%m-%d-%H-%M-%S).png"

if [ ! -d "${DIR}" ]; then
	mkdir "${DIR}"
fi

if [ "$1" = "scr" ]; then
	scrot "${NAME}"
elif [ "$1" = "area" ]; then
	scrot -s "${NAME}"
fi

if [[ $# = 0 ]]; then
	echo "Usage: screenshot [scr|area]"
else
	notify-send "Screenshot taken!" $NAME
	ln -sf "${NAME}" "${DIR}/last.png"
fi
