#!/bin/sh
ICON16="/usr/share/icons/hicolor/16x16/apps/skype.png"
ICON48="/usr/share/icons/hicolor/48x48/apps/skype.png"

notify() {
dbus-send --type=method_call --dest='org.freedesktop.Notifications' \
	/org/freedesktop/Notifications org.freedesktop.Notifications.Notify \
	string:'skype' \
	uint32:58 \
	string:"$1" \
	string:"$2" \
	string:"$3" \
	array:string:'' \
	dict:string:byte:'urgency',1 \
	uint32:3000
}


case $1 in
	msgrecv)
		ACTIVE=$(xdotool getactivewindow getwindowpid)
		PID=$(pidof skype)

		if [[ $ACTIVE != $PID ]]; then
			USER="$2"
			MSG="$3"
			LEN=50
			if [[ ${#MSG} > $LEN  ]]; then
				MSG=$(echo $MSG | fold -w 50)
			fi

			notify $ICON48 "Message received from $USER" "$MSG"
		fi
		$HOME/scripts/scroll_led blink
		;;

	online)
		USER="$2"
		notify $ICON16 "<b>$USER</b> is online"
		;;

	offline)
		USER="$2"
		notify $ICON16 "<b>$USER</b> is offline"
		;;

	*)
		echo "Wut?"
		notify "Wut"
		;;
esac

