#!/bin/bash

args=( $SSH_ORIGINAL_COMMAND )
prog=${args[0]}

case $1 in

	scp)
		flag=${args[1]}
		path=${args[2]}

		case "$prog" in
			scp)
				[ "$flag" != "-t" ] && exit 2
				scp -t $path
				;;
			*sftp-server)
				$SSH_ORIGINAL_COMMAND
				;;
			*)
				exit 1
				;;
		esac
		;;

	rsync)
		[ "$prog" != "rsync" -a "$prog" != "ln" -a "$prog" != "mkdir" ] && exit 3

		$SSH_ORIGINAL_COMMAND
		;;

esac
